--DB03
--p25 ~ 27 12개 SELECT 쿼리
--1.
SELECT HEIGHT 
FROM T_STUDENT 
WHERE HEIGHT >= 180;

--2.
SELECT  name , WEIGHT 
FROM T_STUDENT 
WHERE WEIGHT BETWEEN 60 AND 80;

--3.
SELECT DEPTNO1 제1전공
FROM T_STUDENT 
WHERE DEPTNO1 IN(101, 201);

--4.
SELECT NAME 
FROM T_STUDENT 
WHERE NAME LIKE '김%';

--5.
SELECT NAME , GRADE , HEIGHT 
FROM T_STUDENT 
WHERE GRADE = 4 AND HEIGHT >= 170;

--6.
SELECT NAME, HEIGHT , GRADE , WEIGHT 
FROM T_STUDENT 
WHERE GRADE  = 1 OR WEIGHT >= 80;


--7.
SELECT NAME , GRADE ,HEIGHT ,WEIGHT 
FROM T_STUDENT 
WHERE GRADE = 2 AND (HEIGHT > 180 AND WEIGHT  > 70);

--8.
SELECT NAME , GRADE , HEIGHT , WEIGHT 
FROM T_STUDENT 
WHERE GRADE = 2 AND (HEIGHT  > 180  OR WEIGHT  > 70);

--9.
SELECT  ENAME , HIREDATE 
FROM T_EMP 
WHERE HIREDATE < '1992/01/01';

--10.
SELECT NAME , BIRTHDAY , HEIGHT , WEIGHT 
FROM T_STUDENT 
WHERE GRADE = 1
ORDER BY BIRTHDAY ASC ;

--11.
SELECT NAME 이름, HEIGHT 키
FROM T_STUDENT 
WHERE GRADE  = 1
ORDER BY NAME ASC ;

--12.
SELECT NAME, BIRTHDAY 
FROM T_EMP2 
WHERE BIRTHDAY BETWEEN '1980/01/01' AND '1989/12/31';
